# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: paxos.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bpaxos.proto\x12\x05paxos\x1a\x19google/protobuf/any.proto\"V\n\x0eProposeRequest\x12!\n\x03key\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12!\n\x03val\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"\x1e\n\x0cProposeReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\"@\n\x0ePrepareRequest\x12!\n\x03key\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x0b\n\x03\x62\x61l\x18\x02 \x01(\x03\"w\n\x0cPrepareReply\x12!\n\x03key\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x0e\n\x06result\x18\x02 \x01(\x05\x12\x0e\n\x06maxbal\x18\x03 \x01(\x03\x12$\n\x06maxval\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\"b\n\rAcceptRequest\x12!\n\x03key\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x0b\n\x03\x62\x61l\x18\x02 \x01(\x03\x12!\n\x03val\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\"v\n\x0b\x41\x63\x63\x65ptReply\x12!\n\x03key\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x0e\n\x06result\x18\x02 \x01(\x05\x12\x0e\n\x06maxbal\x18\x03 \x01(\x03\x12$\n\x06maxval\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any2\xaf\x01\n\x05Paxos\x12\x37\n\x07Propose\x12\x15.paxos.ProposeRequest\x1a\x13.paxos.ProposeReply\"\x00\x12\x37\n\x07Prepare\x12\x15.paxos.PrepareRequest\x1a\x13.paxos.PrepareReply\"\x00\x12\x34\n\x06\x41\x63\x63\x65pt\x12\x14.paxos.AcceptRequest\x1a\x12.paxos.AcceptReply\"\x00\x42.\n\x16io.grpc.examples.paxosB\nPaxosProtoP\x01\xa2\x02\x05PAXOSb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'paxos_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026io.grpc.examples.paxosB\nPaxosProtoP\001\242\002\005PAXOS'
  _PROPOSEREQUEST._serialized_start=49
  _PROPOSEREQUEST._serialized_end=135
  _PROPOSEREPLY._serialized_start=137
  _PROPOSEREPLY._serialized_end=167
  _PREPAREREQUEST._serialized_start=169
  _PREPAREREQUEST._serialized_end=233
  _PREPAREREPLY._serialized_start=235
  _PREPAREREPLY._serialized_end=354
  _ACCEPTREQUEST._serialized_start=356
  _ACCEPTREQUEST._serialized_end=454
  _ACCEPTREPLY._serialized_start=456
  _ACCEPTREPLY._serialized_end=574
  _PAXOS._serialized_start=577
  _PAXOS._serialized_end=752
# @@protoc_insertion_point(module_scope)
